name: Java CI with Gradle

on:
  push:
    branches: [ 3.0 ]
  pull_request:
    branches: [ 3.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        java-package: jdk
        check-latest: true
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
